#
# NODE_ENV=development
# NOTE: Set CONFIG_FILE to swap out this config file.
#

app:
  title: 'KUBE Server'
  org': 'DXOS.org'
  theme: 'dark'
  website: 'https://dxos.org'

api:
  path: '/api'
  port: 9004
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'dxos:kube:*'

services:
  app:
    prefix: '/app'
    server: 'https://apollo1.kube.moon.dxos.network'

  wns:
    server: 'https://apollo1.kube.moon.dxos.network/dxos/wns/api'
    webui: 'https://apollo1.kube.moon.dxos.network/dxos/wns/console'

  signal:
    server: 'wss://apollo1.kube.moon.dxos.network/dxos/signal'
    api: 'https://apollo1.kube.moon.dxos.network/dxos/signal/api'

  ipfs:
    server: 'https://apollo1.kube.moon.dxos.network/dxos/ipfs/api'
    gateway: 'https://apollo1.kube.moon.dxos.network/dxos/ipfs/gateway'

  wellknown:
    endpoint: 'https://apollo1.kube.moon.dxos.network/.well-known/dxos'
