app:
  title: 'KUBE Server'
  org': 'DXOS.org'
  theme: 'dark'
  website: 'https://dxos.org'

api:
  path: '/api'
  kubePath: '/kube'
  port: 9004 # TODO(burdon): Standardize and document ports.
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'dxos:kube:*'
