#
# NODE_ENV=production
# NOTE: Set CONFIG_FILE to swap out this config file.
#

app:
  title: 'KUBE Server'
  org': 'DXOS.org'
  theme: 'dark'
  website: 'https://dxos.org'

api:
  path: '/api'
  port: 9004 # TODO(burdon): Standardize and document ports.
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'dxos:kube:*'

services:
  app:
    prefix: '/app'
    server: 'http://127.0.0.1:5999'

  wns:
    server: 'http://127.0.0.1:9473/api'
    webui: 'http://127.0.0.1:9473/console'

  signal:
    server: 'ws://127.0.0.1:4000'
    api: 'http://127.0.0.1:4000/api'

  ipfs:
    server: 'http://127.0.0.1:5001'
    gateway: 'http://127.0.0.1:8888/ipfs/'

  wellknown:
    endpoint: 'http://127.0.0.1:9000/.well-known/dxos'
