//
// Copyright 2021 DXOS.org
//

import * as config from '@dxos/config';

// Generated by webpack-version-file-plugin.
// eslint-disable-next-line import/no-unresolved
import buildInfo from '../dist/version.json';

export const loadSubstrateConfig = async () => new config.Config(
  // TODO(vitalik): Remove the cast when https://github.com/dxos/protocols/pull/380 is merged.
  await (config as any).Dynamics(),
  await config.Envs(),
  config.Defaults(),
  buildInfo
)._config;
