//
// Copyright 2021 DXOS.org
//

// Injected by Webpack NormalModuleReplacementPlugin.
import config from '__CONFIG_FILE__';

// @ts-ignore
// Generated by Webpack VersionFile.
import { build } from '../version.json';

export default Object.assign(config, { build });
