#
# NODE_ENV=production
# NOTE: Set CONFIG_FILE to swap out this config file.
#

app:
  title: 'Console'
  org': 'DXOS.org'
  theme: 'dark'
  website: 'https://dxos.org'
  publicUrl: '/console'

api:
  path: '/api'
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'dxos:console:*'

routes:
  app:
    server: '/app'

  registry:
    server: '/dxos/registry/api'
    webui: '/dxos/registry/console'

  signal:
    api: '/dxos/signal/api'

  ipfs:
    server: '/dxos/ipfs/api'
    gateway: '/dxos/ipfs/gateway'

  wellknown:
    endpoint: '/.well-known/dxos'
