#
# NODE_ENV === production
# NOTE: Set CONFIG_FILE to swap out this config file.
#

app:
  title: 'Console'
  org': 'DXOS'
  theme: 'dark'
  website: 'https://dxos.org'
  publicUrl: '/console'

api:
  server: 'http://127.0.0.1:9004'
  path: '/api'
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'dxos:console:*'

services:
  app:
    prefix: '/app'
    server: 'http://127.0.0.1:5999'

  wns:
    server: 'http://127.0.0.1:9473/api'
    webui: 'http://127.0.0.1:9473/console'

  signal:
    server: 'ws://127.0.0.1:4000'
    api: 'http://127.0.0.1:4000'

  ipfs:
    server: 'http://127.0.0.1:5001'
    gateway: 'http://127.0.0.1:8888/ipfs/'

  wellknown:
    endpoint: 'http://127.0.0.1:9000/.well-known/dxos'
