#
# This config file is loadded **ONLY** in local development.
# It will be replaced by a config/config.json request when served with wire app serve.
#

app:
  title: 'Console'
  org': 'DXOS.org'
  theme: 'dark'
  website: 'https://dxos.org'
  publicUrl: '/console'
registry:
  endpoint: 'wss://dxns1.kube.moon.dxos.network/dxns/ws'

api:
  server: 'https://kube.local'
  path: '/api'
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'dxos:console:*'

services:
  app:
    prefix: '/app'
    server: 'https://enterprise.kube.dxos.network'

  dxns:
    server: 'wss://dxns1.kube.moon.dxos.network/dxns/ws'
    schema:
      cid:
      fqn:
        app: '.dxos.App'
        bot: '.dxos.Bot'
        botFactory: '.dxos.BotFactory'
        KUBE: '.dxos.KUBE'
        service: '.dxos.Service'
        file: '.dxos.File'
  signal:
    server: 'wss://enterprise.kube.dxos.network/dxos/signal'
    api: 'https://enterprise.kube.dxos.network/dxos/signal/api'

  ipfs:
    server: 'https://enterprise.kube.dxos.network/dxos/ipfs/api'
    gateway: 'https://enterprise.kube.dxos.network/dxos/ipfs/gateway'

  wellknown:
    endpoint: 'https://enterprise.kube.dxos.network/.well-known/dxos'
