#
# This config file is loadded **ONLY** in local development.
# It will be replaced by a config/config.json request when served with dx app serve.
#

version: 1

runtime:
  props:
    title: 'Console'

  app:
    theme: 'dark'
    website: 'https://dxos.org'
    publicUrl: '/console'

  services:
    kube:
      endpoints:
        logs: '/kube/logs'
        services: '/kube/services'

    app:
      prefix: "/app"
      server: https://discovery.kube.dxos.network

    dxns:
      # server: wss://discovery.kube.dxos.network/dxns/ws
      # TODO(wittjosiah): Temp, revert
      server: 'ws://127.0.0.1:9945'
  
    ipfs:
      server: https://discovery.kube.dxos.network/dxos/ipfs/api
      gateway: https://discovery.kube.dxos.network/dxos/ipfs/gateway/

    signal:
      server: wss://discovery.kube.dxos.network/dxos/signal
      api: https://discovery.kube.dxos.network/dxos/signal/api

    bot:
      topic: d4d8f4aa6999ff87b00b2644117bcf9dd62c7ae7a70118264b2e1d286402c9fa

    ice:
    - urls: stun:discovery.kube.dxos.network:3478
    - urls: turn:discovery.kube.dxos.network:3478
      username: dxos
      credential: dxos
    - urls: stun:discovery.kube.dxos.network:3478
    - urls: turn:discovery.kube.dxos.network:3478
      username: dxos
      credential: dxos
