#
# This config file is loadded **ONLY** in local development.
# It will be replaced by a config/config.json request when served with dx app serve.
#

version: 1

runtime:
  props:
    title: 'Console'

  app:
    theme: 'dark'
    website: 'https://dxos.org'
    publicUrl: '/console'

  services:
    kube:
      endpoints:
        logs: '/kube/logs'
        services: '/kube/services'

    app:
      prefix: '/app'
      server: 'https://enterprise.kube.dxos.network'

    dxns:
      # TODO(wittjosiah): Temp, revert
      server: 'ws://127.0.0.1:9945'

    signal:
      server: 'wss://enterprise.kube.dxos.network/dxos/signal'
      api: 'https://enterprise.kube.dxos.network/dxos/signal/api'
      # TODO(egorgripasov): Temp, replace with enterprise.
      status: 'https://test-signal2.kube.dxos.network/dxos/signal/status'

    ipfs:
      server: 'https://enterprise.kube.dxos.network/dxos/ipfs/api'
      gateway: 'https://enterprise.kube.dxos.network/dxos/ipfs/gateway'
