#
# App-specific constants and defaults.
#

version: 1

runtime:
  props:
    title: "Console"
  app:
    org': 'DXOS.org'
    theme: 'dark'
    website: 'https://dxos.org'
    publicUrl: '/console'
  system:
    debug: 'dxos:console:*'
