#
# App-specific constants and defaults.
#

app:
  title: 'Console'
  org': 'DXOS.org'
  theme: 'dark'
  website: 'https://dxos.org'
  publicUrl: '/console'

system:
  debug: 'dxos:console:*'

devKeyring: true

types:
  Domain:
    name: Option<Text>
    owners: Vec<AccountId>
  Auction:
    name: Vec<u8>
    highest_bidder: AccountId
    highest_bid: u128
    end_block: BlockNumber
    closed: bool
  Record:
    data: Vec<u8>
    schema: Multihash
    messageFqn: Text
  Multihash: "[u8; 34]"
  DomainKey: "[u8; 32]"

build:
  version: ''
