#
# App-specific constants and defaults.
#

version: 1

runtime:
  props:
    title: 'Console'

  app:
    theme: 'dark'
    website: 'https://dxos.org'
    publicUrl: '/console'

  system:
    debug: 'dxos:console:*'
