//
// Copyright 2021 DXOS.org
//

import * as config from '@dxos/config';

// Generated by webpack-version-file-plugin.
// eslint-disable-next-line import/no-unresolved
import buildInfo from '../dist/version.json';

/**
 * Constructs a global config based on the precendence of other configurations.
 * NOTE: We do not use environment variables.
 *
 * The order of precedence:
 * - Stored config (e.g., user configurable options).
 * - Build-target specific config (e.g., servers).
 * - App-specific defaults and constants.
 * - Build info (generated by webpack).
 *
 * TODO(burdon): Define global schema (across all apps/modules).
 */

export const loadConfig = async () => new config.Config(
  // TODO(vitalik): Remove the cast when https://github.com/dxos/protocols/pull/380 is merged.
  await (config as any).Dynamics(),
  await config.Envs(),
  config.Defaults(),
  buildInfo
);
