# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR - Build and Test

on: pull_request

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Build and test
        run: |
          git config --global user.email "npm@dxos.org"
          git config --global user.name "DXOS"

          yarn install
          yarn ci

        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          WIRE_WNS_USER_KEY: ${{secrets.wns_user_key}}
          WIRE_WNS_BOND_ID: ${{secrets.wns_bond_id}}
          WIRE_PROFILE_URL: ${{secrets.wire_profile_url}}
          WIRE_PROFILE: ci
