on:
  push:
    branches:
      - main

name: Publish packages to NPM, apps to DXNS
jobs:
  publish:
    runs-on: [self-hosted, dind-actions-runner]
    timeout-minutes: 25
    strategy:
      matrix:
        node-version: [16.1]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: false
    - uses: actions/setup-node@v1
      with:
        node-version: 16.1
    - name: Check, install and build
      run: |
        \. "$NVM_DIR/nvm.sh" && nvm install ${{ matrix.node-version }} && nvm use ${{ matrix.node-version }}

        npm install -g @microsoft/rush pnpm

        # Install dependencies
        echo "::group::Install"
        node common/scripts/install-run-rush.js install
        echo "::endgroup::"

        # Build with tests
        node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build --verbose
        node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js test --verbose
    - name: Publish latest to NPM
      run:  |
        \. "$NVM_DIR/nvm.sh" && nvm use ${{ matrix.node-version }}
        npm install -g @microsoft/rush pnpm

        # Publish under "latest" tag
        node common/scripts/install-run-rush.js publish --publish --include-all --tag latest
    - name: Publish dev to NPM
      run:  |
        \. "$NVM_DIR/nvm.sh" && nvm use ${{ matrix.node-version }}
        npm install -g @microsoft/rush pnpm

        git config --global user.email "ci@dxos.org"
        git config --global user.name "ci"

        # Create a temporary bump of versions
        node common/scripts/install-run-rush.js version --bump --override-bump prerelease --override-prerelease-id dev

        # Include a commit hash in the version
        SUBST="s/dev.0/dev.$(git rev-parse --short HEAD)/g"
        FILEPATH='./common/config/rush/version-policies.json'
        sed -i $SUBST $FILEPATH # Caution: on macOS that would be `sed -i '' $SUBST $FILEPATH`
        node common/scripts/install-run-rush.js version --ensure-version-policy

        # Publish under "dev" tag
        node common/scripts/install-run-rush.js publish --publish --include-all --tag dev
  publish-apps:
    runs-on: [self-hosted, dind-actions-runner]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      DX_PROFILE_URL: ${{ secrets.dx_profile_url }}
      DX_DXNS_USER_URI: ${{ secrets.DX_DXNS_USER_URI }}
      DX_PROFILE: ci
    timeout-minutes: 25
    strategy:
      matrix:
        node-version: [16.0]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check, install and build
      run: |
        \. "$NVM_DIR/nvm.sh" && nvm use ${{ matrix.node-version }}

        npm install -g @microsoft/rush pnpm

        # Install dependencies
        echo "::group::Install"
        node common/scripts/install-run-rush.js install
        echo "::endgroup::"

        # Quick build
        node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build --verbose
    - name: Initialize CLI
      run: |
        set -e
        \. "$NVM_DIR/nvm.sh" && nvm use ${{ matrix.node-version }}
        npm install -g yarn

        yarn global add @dxos/cli@v2.8.2-alpha.0
        yarn global add @dxos/cli-dxns@v2.8.2-alpha.0
        yarn global add @dxos/cli-app@v2.8.2-alpha.0
    - name: Publish apps
      run:  |
        \. "$NVM_DIR/nvm.sh" && nvm use ${{ matrix.node-version }}
        export PATH="$PATH:$(yarn global bin)"
        ./common/scripts/publish-apps.sh
