# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on: pull_request

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Build and publish
        run: |
          yarn install

          # Publish to registry
          DEBUG='dxos:cli' yarn wire profile init --name $WIRE_PROFILE --template-url "$WIRE_PROFILE_URL"
          export PKG_CHANNEL="@alpha"
          scripts/publish_app.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          WIRE_WNS_USER_KEY: ${{secrets.wns_user_key}}
          WIRE_WNS_BOND_ID: ${{secrets.wns_bond_id}}
          WIRE_PROFILE_URL: ${{secrets.wire_profile_url}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          WIRE_PROFILE: ci
